apiVersion: v1
kind: Service
metadata:
  name: scheduler-api
  namespace: default
  labels:
    app: scheduler-api
spec:
  type: ClusterIP
  selector:
    app: scheduler-api
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-api-loadbalancer
  namespace: default
  labels:
    app: scheduler-api
spec:
  type: LoadBalancer
  selector:
    app: scheduler-api
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
